-- Create table for Shop Page Hero content
create table if not exists public.shop_hero_content (
    id bigint generated by default as identity primary key,
    slides jsonb default '[]'::jsonb, -- Array of {id, image_url, title, subtitle, link}
    banners jsonb default '[]'::jsonb, -- Array of {id, position, image_url, title, link}
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.shop_hero_content enable row level security;

-- Policies
create policy "Enable read access for all users" on public.shop_hero_content
    for select using (true);

create policy "Enable insert for authenticated users only" on public.shop_hero_content
    for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.shop_hero_content
    for update using (auth.role() = 'authenticated');

-- Insert initial empty row if not exists
insert into public.shop_hero_content (slides, banners)
select '[]'::jsonb, '[]'::jsonb
where not exists (select 1 from public.shop_hero_content);
